### ISSUE TITLE
不好意思，没找到更好方式提问。。希望能解答下。谢谢！

### ISSUE THREAD

**Issue by live17909** [ikidou/Retrofit2Demo#1]
// 实现的效果与上面想同
        Map<String, Object> map = new HashMap<>();
        map.put("username", "怪盗kidou");
        map.put("age", 24);

如果需要传字符数组，如何传呢？。。
params.put("pmId1[]\"; filename=\"ame\"", toRequestBody("pmId11"));
        params.put("pmId1[]\"; filename=\"ame\"", toRequestBody("pmId12"));
        params.put("pmId1[]\"; filename=\"ame\"", toRequestBody("pmId13"));
这种方式传好象服务器解析不了，？，求助，谢谢！

**Comment by live17909** [comment]
3189594713@qq.com
忘记留邮箱了。希望能收到回复。谢谢1

**Comment by ikidou** [comment]
上面的那个例子是`FieldMap`和`FormUrlEncoded`的例子，我看你想要的是上传文件，那就不能用`FieldMap`了，只能是用`Multipart`和`Part`或`PartMap`。

**Comment by live17909** [comment]
谢谢。确实是想传字符串数组。。文件的上传是正常的。。

**Comment by ikidou** [comment]
如果是字符串数组，那你就只能用 `@Field("pmId1[]") String[] strArr` ，Map里面的键唯一的，你写了三个最后也只留一个啊，再说只有只Multipart 才有`filename=XXX`

**Comment by live17909** [comment]
试了下也是不行。。
@Field parameters can only be used with form encoding. (parameter #3)
for method ApiInterface.submitBriberyInvestigation
java.lang.IllegalArgumentException: @Field parameters can only be used with form encoding. (parameter #3)
for method ApiInterface.submitBriberyInvestigation
    at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:667)
    at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:658)
    at retrofit2.ServiceMethod$Builder.parameterError(ServiceMethod.java:676)
    at retrofit2.ServiceMethod$Builder.parseParameterAnnotation(ServiceMethod.java:477)
    at retrofit2.ServiceMethod$Builder.parseParameter(ServiceMethod.java:328)
    at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:201)
    at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:166)
    at retrofit2.Retrofit$1.invoke(Retrofit.java:145)
    at java.lang.reflect.Proxy.invoke(Proxy.java:393)
    at $Proxy0.submitBriberyInvestigation(Unknown Source)
    at cn.ac.iscas.gz.ygjw.ui.DocSurveyActivityFragment.toDo(DocSurveyActivityFragment.java:704)
    at cn.ac.iscas.gz.ygjw.ui.DocSurveyActivity.toDoRight(DocSurveyActivity.java:36)
    at cn.ac.iscas.gz.ygjw.base.BaseActivity.onMenuItemClick(BaseActivity.java:174)
    at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:169)
    at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:760)
    at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
    at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
    at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
    at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
    at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:618)
    at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
    at android.view.View.performClick(View.java:5204)
    at android.view.View$PerformClick.run(View.java:21153)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ikidou** [comment]
。。。，你没给方法加 `@FormUrlEncoded`，这个和`@Multipart`不能共用。

**Comment by live17909** [comment]
有先后顺序吗？
Only one encoding annotation is allowed.
for method ApiInterface.submitBriberyInvestigation
java.lang.IllegalArgumentException: Only one encoding annotation is allowed.
for method ApiInterface.submitBriberyInvestigation
    at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:667)
    at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:658)
    at retrofit2.ServiceMethod$Builder.parseMethodAnnotation(ServiceMethod.java:266)
    at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:169)
    at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:166)
    at retrofit2.Retrofit$1.invoke(Retrofit.java:145)
    at java.lang.reflect.Proxy.invoke(Proxy.java:393)
    at $Proxy0.submitBriberyInvestigation(Unknown Source)

**Comment by ikidou** [comment]
Only one encoding annotation is allowed. 只允许有一个encoding 注解，自己翻译就知道是啥意思了吧

**Comment by live17909** [comment]
Shutting down VM
@PartMap parameters can only be used with multipart encoding. (parameter #2)
for method ApiInterface.submitBriberyInvestigation
java.lang.IllegalArgumentException: @PartMap parameters can only be used with multipart encoding. (parameter #2)

_只一个也不行_

**Comment by live17909** [comment]
@Multipart
    @FormUrlEncoded
    @POST("publicService.do?action=submitBriberyInvestigation&dataType=mobile&ecafeNotRedirect=true")
    Observable<CommitResult> submitBriberyInvestigation(@Query("ecafeToken") String ecafeToken, @PartMap Map<String, RequestBody> map,
                                                        @Field("projectManager[]") String[] strArr);
//                                                        @PartMap Map<String, String[]> pMap);
//                                                 ,@PartMap Map<String, String[]> projectManagerId);

**Comment by live17909** [comment]
可能我需求比较复杂些。。谢谢你的耐心帮忙。

**Comment by ikidou** [comment]
`@Multipart`和`@FormUrlEncoded`不可以一起用！ 你要上传文件才用`@Multipart`，不用`@Multipart`也就不能用 `@Part`和`@PartMap`，

**Comment by live17909** [comment]
也有文件上传

**Comment by ikidou** [comment]
那你用可以用`@Part List<Part> parts` 或者用 `@Part("pmId1[]") List<RequestBody>`

**Comment by live17909** [comment]
服务端解析不到，pmId1是空。。。

**Comment by live17909** [comment]
刚才用的是这个@Part("pmId1[]") List<RequestBody>

**Comment by ikidou** [comment]
我只是帮你上传字符串数组，至于是不是按后台的要求传的，那就是你和后台的问题了。

**Comment by live17909** [comment]
谢谢！
